# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('engineDisplacement', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(blank=True, max_length=10)),
                ('seler_description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=60)),
                ('doors', models.PositiveIntegerField(null=True)),
                ('power', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(null=True)),
                ('milleageKM', models.PositiveIntegerField(null=True)),
                ('json_rep', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_full_info', models.TextField(blank=True)),
                ('json_basic_info', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('searchable_words', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Seller'),
        ),
    ]
