# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
