# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_favorite_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='owner',
        ),
    ]
