# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_favorite_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('discounted_price', models.PositiveIntegerField()),
                ('display', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('image2', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
            ],
        ),
    ]
