# Generated by Django 2.1.2 on 2019-12-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190315_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='foto.jpg', upload_to='cars'),
        ),
    ]
